console.log("Addition");
console.log("50 + 5");
console.log(50 + 5);
console.log("Subtraction");
console.log("90-1");
console.log(90-1);
console.log("Multiplication");
console.log("11111 * 7 ");
console.log(11111 * 7 );
console.log("Division");
console.log("400/25");
console.log(400/25);
console.log("Modulo!!");
console.log("27% 2");
console.log(27% 2);
console.log("0/0");
console.log(0/0);
console.log("1+NaN");
console.log(1+NaN);
console.log("4 + 3 * 4 / 2");
console.log(4 + 3 * 4 / 2);
console.log("13 % 5) ** 2");
console.log((13 % 5) ** 2);
console.log("200+ 0/0");
console.log(200+ 0/0);
let someName = "Khan";
console.log("let someName = \"Khan\";");
console.log(someName);
let year = 1985;
console.log("let year = 1985;");
console.log(year);
let hens = 4;
let roosters = 2;
console.log("let hens = 4;\nlet roosters = 2;");
console.log(hens + roosters);
console.log("hens-1");
console.log(hens-1);
console.log("hens");
console.log(hens);
console.log("hens = hens - 1");
console.log(hens = hens - 1);
const hens1 = 4;
console.log("const hens1 = 4;");
hens = 20;
console.log("hens = 20;");
const age = 17;
console.log("const age = 17;");
console.log("age = age+1;");
let numPuppies = 23;
console.log("let numPuppies = 23;");
console.log(numPuppies);
numPuppies = false;
console.log("numPuppies = false;");    
console.log(numPuppies);
numPuppies = 100;
console.log("numPuppies = 100;");
console.log(numPuppies);
let firstName = "Ziggy"
console.log("let firstName = \"Ziggy\"");
console.log(firstName);
let animal = 'dog';
console.log("let animal = 'dog';");
console.log(animal);
let msg = "I'm a king";   
console.log("let msg = \"I'm a king\";");
console.log(msg);
let yellmsg = msg.toUpperCase();
console.log("let yellmsg = msg.toUpperCase();");
console.log(yellmsg);
let msg2 = "I'm A KING";   
console.log("let msg2 = \"I'm A KING\";");
console.log(msg2);
let yellmsg2 = msg2.toLowerCase();
console.log("let yellmsg2 = msg2.toLowerCase();");
console.log(yellmsg2);
let gree = '    leave me alone    ';
console.log("let gree = '    leave me alone    ';");
console.log(gree);
console.log("gree.trim();");
console.log(gree.trim());
let tvShow = 'catdog';
console.log("let tvShow = 'catdog';");
console.log(tvShow);
console.log("tvShow.indexOf('cat');");
console.log(tvShow.indexOf('cat'));
console.log("tvShow.indexOf('dog');");
console.log(tvShow.indexOf('dog'));
console.log("tvShow.indexOf('z');");
console.log(tvShow.indexOf('z'));
let str = 'supercalifragilisticexpialidocious';
console.log("let str = 'supercalifragilisticexpialidocious';");
console.log(str);
console.log("str.slice(0,5);");
console.log(str.slice(0,5));
console.log("str.slice(5);");
console.log(str.slice(5));
let annoyingLaugh = 'teehee so funny! teehee!';
console.log("let annoyingLaugh = 'teehee so funny! teehee!';");
console.log(annoyingLaugh);
console.log("annoyingLaugh.replace('teehee', 'haha')");
console.log(annoyingLaugh.replace('teehee', 'haha'));
let item = 'cucumbers';
console.log("let item = 'cucumbers';");
console.log(item);
let price = 1.99;
console.log("let price = 1.99;");
console.log(price);
let quantity = 4;
console.log("let quantity = 4;");
console.log(quantity);
console.log(`You bought ${quantity} ${item}, total price: $${price*quantity}`);
console.log("Math.PI");
console.log(Math.PI);
console.log("Math.round(4.9)");
console.log(Math.round(4.9));
console.log("Math.abs(-456)");
console.log(Math.abs(-456));
console.log("Math.pow(2,5)");
console.log(Math.pow(2,5));
console.log("Math.floor(3.9999)");
console.log(Math.floor(3.9999));
console.log("Math.random()");
console.log(Math.random());
console.log("parseInt('24')");
console.log(parseInt('24'));
console.log("parseInt('24.987')");
console.log(parseInt('24.987'));
console.log("parseInt('28dayslater')");
console.log(parseInt('28dayslater'));
console.log("parseFloat('24.987')");
console.log(parseFloat('24.987'));
console.log("parseFloat('7')");
console.log(parseFloat('7'));
console.log("parseFloat('i ate 3 shramp')");
console.log(parseFloat('i ate 3 shramp'));
console.log("10 > 1;");
console.log(10 > 1);
console.log("0.2 > 0.3");
console.log(0.2 > 0.3);
console.log("-10 < 0");
console.log(-10 < 0);
console.log("50.5 < 5");
console.log(50.5 < 5);
console.log("0.5 <= 0.5");
console.log(0.5 <= 0.5);
console.log("99 >= 4");
console.log(99 >= 4);
console.log("99 >= 99");
console.log(99 >= 99);
console.log("'a' < 'b'");
console.log('a' < 'b');
console.log("'A' > 'a'");
console.log('A' > 'a');
console.log("5 == 5");
console.log(5 == 5);
console.log("'b' == 'c'");
console.log('b' == 'c');
console.log("7 == '7'");
console.log(7 == '7');
console.log("0 == ''");
console.log(0 == '');
console.log("true == false");
console.log(true == false);
console.log("0 == false");
console.log(0 == false);
console.log("5 === 5");
console.log(5 === 5);
console.log("1 === 2");
console.log(1 === 2);
console.log("2 === '2'");
console.log(2 === '2');
console.log("false === 0");
console.log(false === 0);
console.log("10 != '10'");
console.log(10 != '10');
console.log("10 !== '10'");
console.log(10 !== '10');
console.log("1 <= 4 && 'a' === 'a'");
console.log(1 <= 4 && 'a' === 'a');
console.log("9 > 10 && 9 >= 9");
console.log(9 > 10 && 9 >= 9);
console.log("'abc'.length === 3 && 1+1 === 4");
console.log('abc'.length === 3 && 1+1 === 4);
console.log("1 !== 1 || 10 === 10");
console.log(1 !== 1 || 10 === 10);
console.log("10/2 === 5 || null");
console.log(10/2 === 5 || null);
console.log("0 || undefined");
console.log(0 || undefined);
console.log("!null");
console.log(!null);
console.log("! (0 === 0)");
console.log(! (0 === 0));
console.log("!(3 <= 4)");
console.log(!(3 <= 4));
let students = [];
console.log("let students = [];");
console.log(students);
let colors = ['red', 'orange', 'yellow'];
console.log("let colors = ['red', 'orange', 'yellow'];");
console.log(colors);
let lottoNums = [19,22,56,12,51];
console.log("let lottoNums = [19,22,56,12,51];")
console.log(lottoNums);
let stuff = [true, 68, 'cat', null];
console.log("let stuff = [true, 68, 'cat', null];");
console.log(stuff);
console.log("colors.length");
console.log(colors.length);
console.log("colors[0]");
console.log(colors[0]);
console.log("colors[1]");
console.log(colors[1]);
console.log("colors[2]");
console.log(colors[2]);
console.log("colors[3]");
console.log(colors[3]);
console.log("colors [4]");
console.log(colors [4]);
console.log("colors[0] = 'red';");
console.log(colors[0] = 'red');
console.log("colors[2] = 'yellow'");
console.log(colors[2] = 'yellow');
console.log("colors[3] = 'green'");
console.log(colors[3] = 'green');
console.log("colors[4] = 'blue'");
console.log(colors[4] = 'blue');
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
console.log("");
console.log();
